import json
import os
import sys
from unittest.mock import MagicMock, patch

# Add paths to sys.path to find backend modules and mock-data generator
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "mock-data")))

from clustering import cluster_signals
from models import FanSignal


def get_mock_signals():
    """Load mock signals generated by generate_signals.py.
    If signals.json doesn't exist, call generate_mock_data() to create it.
    """
    mock_data_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "mock-data"))
    signals_json = os.path.join(mock_data_dir, "signals.json")

    if not os.path.exists(signals_json):
        from generate_signals import generate_mock_data

        generate_mock_data()

    with open(signals_json, "r") as f:
        signals_data = json.load(f)

    return [FanSignal(**s) for s in signals_data]


@patch("clustering.Anthropic")
def test_cluster_signals_success(mock_anthropic_class):
    """Test that cluster_signals correctly identifies the spike cluster and excludes unrelated background signals."""
    # Ensure ANTHROPIC_API_KEY is present in the environment for the check
    os.environ["ANTHROPIC_API_KEY"] = "mock_key_for_testing"

    # 1. Load mock signals from generate_signals.py dataset
    all_signals = get_mock_signals()

    # Take all 45 spike signals and a sample of 10 background signals to keep payload size reasonable
    spike_signals = [s for s in all_signals if s.id.startswith("sig_spike_")]
    bg_signals = [s for s in all_signals if not s.id.startswith("sig_spike_")][:10]

    test_signals = spike_signals + bg_signals

    spike_ids = [s.id for s in spike_signals]
    bg_ids = [s.id for s in bg_signals]

    # 2. Mock the Anthropic messages.create call to simulate Claude's clustering response
    mock_client = MagicMock()
    mock_response = MagicMock()
    mock_block = MagicMock()

    # Mock return JSON from Claude
    claude_json_response = [
        {
            "signal_ids": spike_ids,
            "zone": "Zone C",
            "topic": "Major Restroom Flooding and Water Leak",
            "confidence_score": 0.98,
        }
    ]

    mock_block.text = json.dumps(claude_json_response)
    mock_response.content = [mock_block]
    mock_client.messages.create.return_value = mock_response
    mock_anthropic_class.return_value = mock_client

    # 3. Run the clustering function
    clusters = cluster_signals(test_signals)

    # 4. Assertions
    # Verify the mock Anthropic client was called with correct parameters
    mock_client.messages.create.assert_called_once()
    call_kwargs = mock_client.messages.create.call_args[1]
    assert call_kwargs["model"] == "claude-3-5-sonnet-20240620"

    # Verify the prompt contained both spike and background signal content
    prompt = call_kwargs["messages"][0]["content"]
    assert "sig_spike_" in prompt
    assert bg_ids[0] in prompt

    # Verify the output cluster structure and values
    assert len(clusters) == 1
    spike_cluster = clusters[0]

    assert spike_cluster.zone == "Zone C"
    assert "restroom" in spike_cluster.topic.lower() or "flood" in spike_cluster.topic.lower()

    # Assert confidence score is above a threshold of 0.85
    assert spike_cluster.confidence_score >= 0.85
    assert spike_cluster.confidence_score == 0.98

    # Assert all spike signals are included in the cluster
    assert len(spike_cluster.signal_ids) == len(spike_ids)
    assert set(spike_cluster.signal_ids) == set(spike_ids)

    # Assert normal, unrelated background signals are NOT incorrectly grouped in the cluster
    for bg_id in bg_ids:
        assert bg_id not in spike_cluster.signal_ids


def test_cluster_signals_no_api_key():
    """Test that cluster_signals returns an empty list early if ANTHROPIC_API_KEY is not set."""
    # Temporarily remove ANTHROPIC_API_KEY
    old_key = os.environ.get("ANTHROPIC_API_KEY")
    if "ANTHROPIC_API_KEY" in os.environ:
        del os.environ["ANTHROPIC_API_KEY"]

    try:
        signals = [
            FanSignal(id="sig_1", source_type="voice", location_zone="Zone A", raw_text="Test", sentiment_score=0.0)
        ]
        clusters = cluster_signals(signals)
        assert clusters == []
    finally:
        # Restore key
        if old_key:
            os.environ["ANTHROPIC_API_KEY"] = old_key
